# Generated by Django 5.1.3 on 2024-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('MD', 'Moderator'), ('SL', 'Seller'), ('BY', 'Buyer')], max_length=2)),
            ],
        ),
    ]
