# Generated by Django 5.1.3 on 2024-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='desciprtion',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('r', 'REVIEW'), ('x', 'REJECT'), ('a', 'ACCEPT')], default='r', max_length=1),
        ),
    ]
