# Generated by Django 5.1.3 on 2024-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_desciprtion_apartment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='daily_price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
